name: bot-test

on:
  push:
    branches:
      - test # run every time there is a push to main branch
jobs:

  psicotuiterbot-post:
    runs-on: ubuntu-20.04
    env: #  twitter API keys (used to authenticate) defined in the gh actions environment
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_KEY_SECRET: ${{ secrets.TWITTER_CONSUMER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      RENV_PATHS_ROOT: ~/.local/share/renv
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
            use-public-rspm: true
        
      - name: Cache packages
        uses: actions/cache@v1
        with:
            path: ${{ env.RENV_PATHS_ROOT }}
            key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
            restore-keys: |
                ${{ runner.os }}-renv-
                
      - name: Restore packages
        shell: Rscript {0}
        run: |
            if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
            renv::restore()
            
      - name: Test block script
        run: |
          sed -i -e 's/\r$//' sh/block.sh
          chmod +x sh/block.sh
          sh/block.sh
        shell: bash
        
      - name: Test rt script
        run: |
          sed -i -e 's/\r$//' sh/rt.sh
          chmod +x sh/rt.sh
          sh/rt.sh
        shell: bash
        
        
