name: psicotuiterbot

on:
  schedule:
    - cron: '*/15 * * * *' # run every 15th minute
  push:
    branches:
      - main # run every time there is a push to main branch

jobs:

  psicotuiterbot-post:
    runs-on: macOS-latest
    env: #  twitter API keys (used to authenticate) defined in the gh actions environment
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_KEY_SECRET: ${{ secrets.TWITTER_CONSUMER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-renv@v1
        with:
          cache-version: 1
      - name: Restore packages using renv
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Create and post tweet
        run: Rscript R/bot.R
